export const cityTypes = {
  LOADING_START: "LOADING_START",
  LOADING_STOP: "LOADING_STOP",
  FETCH_ALL_CITIES_SUCCESS: "FETCH_ALL_CITIES_SUCCESS",
  FETCH_ALL_CITIES_ERROR: "FETCH_ALL_CITIES_ERROR",

  CREATE_NEW_CITY_SUCCESS: "CREATE_NEW_CITY_SUCCESS",
  CREATE_NEW_CITY_ERROR: "CREATE_NEW_CITY_ERROR",
  CLEAR_AFTER_CITY_CREATION: "CLEAR_AFTER_CITY_CREATION",

  UPDATE_CITY_SUCCESS: "UPDATE_CITY_SUCCESS",
  UPDATE_CITY_ERROR: "UPDATE_CITY_ERROR",
  CLEAR_AFTER_CITY_UPDATE: "CLEAR_AFTER_CITY_UPDATE",

  DELETE_CITY_SUCCESS: "DELETE_CITY_SUCCESS",
  DELETE_CITY_ERROR: "DELETE_CITY_ERROR",
  CLEAR_AFTER_CITY_DELETION: "CLEAR_AFTER_CITY_DELETION",

  FETCH_CITY_SUCCESS: "FETCH_CITY_SUCCESS",
  FETCH_CITY_ERROR: "FETCH_CITY_ERROR",

  FILTER_ALL_CITIES_SUCCESS: "FILTER_ALL_CITIES_SUCCESS",
  FILTER_ALL_CITIES_ERROR: "FILTER_ALL_CITIES_ERROR",
};
