export const locationTypes = {
  LOADING_START: "LOADING_START",
  LOADING_STOP: "LOADING_STOP",
  FETCH_ALL_LOCATION_SUCCESS: "FETCH_ALL_LOCATION_SUCCESS",
  FETCH_ALL_LOCATION_ERROR: "FETCH_ALL_LOCATION_ERROR",

  CREATE_NEW_LOCATION_SUCCESS: "CREATE_NEW_LOCATION_SUCCESS",
  CREATE_NEW_LOCATION_ERROR: "CREATE_NEW_LOCATION_ERROR",
  CLEAR_AFTER_LOCATION_CREATION: "CLEAR_AFTER_LOCATION_CREATION",

  UPDATE_LOCATION_SUCCESS: "UPDATE_LOCATION_SUCCESS",
  UPDATE_LOCATION_ERROR: "UPDATE_LOCATION_ERROR",
  CLEAR_AFTER_LOCATION_UPDATE: "CLEAR_AFTER_LOCATION_UPDATE",

  DELETE_LOCATION_SUCCESS: "DELETE_LOCATION_SUCCESS",
  DELETE_LOCATION_ERROR: "DELETE_LOCATION_ERROR",
  CLEAR_AFTER_LOCATION_DELETION: "CLEAR_AFTER_LOCATION_DELETION",

  FETCH_LOCATION_SUCCESS: "FETCH_LOCATION_SUCCESS",
  FETCH_LOCATION_ERROR: "FETCH_LOCATION_ERROR",

  FILTER_ALL_LOCATIONS_SUCCESS: "FILTER_ALL_LOCATIONS_SUCCESS",
  FILTER_ALL_LOCATIONS_ERROR: "FILTER_ALL_LOCATIONS_ERROR",
};
